config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :challenges, only: [:index, :show] do
    resources :messages, only: [:new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :messages, dependent: :destroy
  validates :name, :module, :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :challenge

  has_one_attached :file

  validate :file_size_validation
  validates :content, length: { minimum: 10, maximum: 1000 }, if: -> { role == "user" }

  MAX_FILE_SIZE_MB = 10

  private

  def file_size_validation
    if file.attached? && file.byte_size > MAX_FILE_SIZE_MB.megabytes
      errors.add(:file, "size must be less than #{MAX_FILE_SIZE_MB}MB")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_challenges

  private

  def set_challenges
    @challenges = Challenge.all
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = Challenge.all
  end

  def show
    @challenge = Challenge.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  SYSTEM_PROMPT = <<~PROMPT
    You are a Teaching Assistant.

    I am a student at the Le Wagon Web Development Bootcamp, learning how to code.

    Help me break down my problem into small, actionable steps, without giving away solutions.

    Answer concisely in markdown.
  PROMPT

  def new
    @challenge = Challenge.find(params[:challenge_id])
    @message = Message.new
  end

  def create
    @challenge = Challenge.find(params[:challenge_id])
    @message = Message.new(message_params)
    @message.challenge = @challenge
    @message.role = 'user'
    if @message.save
      if @message.file.attached?
        process_file(@message.file)
      else
        send_question
      end

      Message.create(role: "assistant", content: @response.content, challenge: @challenge)
      redirect_to challenge_messages_path(@challenge), notice: "Message was successfully created."
    else
      render :new
    end
  end

  def index
    @challenge = Challenge.find(params[:challenge_id])
  end

  private

  def send_question(model: "gpt-4.1-nano", with: {})
    @ruby_llm_chat = RubyLLM.chat(model: model)
    @response = @ruby_llm_chat.with_instructions(instructions).ask(@message.content, with: with)
  end

  def process_file(file)
    if file.content_type == 'application/pdf'
      send_question(model: "gemini-2.0-flash", with: { pdf: @message.file.url })
    elsif file.image?
      send_question(model: "gpt-4o", with: { image: @message.file.url })
    elsif file.audio?
      @ruby_llm_chat = RubyLLM.chat(model: "gpt-4o-audio-preview") # audio-capable model
      Dir.mktmpdir do |dir|
        require 'open-uri'
        temp_file_path = File.join(dir, @message.file.filename.to_s)

        URI.open(@message.file.url) do |remote_file|
          File.open(temp_file_path, 'wb') do |file|
            file.write(remote_file.read)
          end
        end
        @response = @ruby_llm_chat.ask(@message.content, with: {audio: temp_file_path})
      end
    end
  end

  def message_params
    params.require(:message).permit(:content, :file)
  end

  def challenge_context
    "Here is the context of the challenge the student is working on: \n#{@challenge.content}."
  end

  def instructions
    [SYSTEM_PROMPT, challenge_context, @challenge.system_prompt].compact.join("\n\n")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(text)
    Kramdown::Document.new(text, input: 'GFM', syntax_highlighter: "rouge").to_html
  end
end

app/views/challenges/index.html.erb
<h1>Challenges</h1>

<ul>
  <% @challenges.each do |challenge| %>
    <li><%= link_to challenge.name, challenge_path(challenge) %></li>
  <% end %>
</ul>

app/views/challenges/show.html.erb
<h1><%= @challenge.name %></h1>

<%= raw(render_markdown(@challenge.content)) %>

<%= link_to "Ask for help", new_challenge_message_path(@challenge), class: "btn btn-primary" %>

<%= link_to "View messages", challenge_messages_path(@challenge), class: "link-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAiChallenges</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container-fluid">
      <div class="row" data-controller="toggle">
        <nav class="col-md-2 sidebar pt-3" data-toggle-target="hideable">
          <%= render "shared/sidenav", challenges: @challenges %>
        </nav>
        <div class="col-md-10 my-4">
          <%= render "shared/flashes" %>
          <%= link_to "#",
                      class: "nav-link text-dark d-none",
                      data: {
                        action: 'click->toggle#call',
                        toggle_target: 'show'
                      } do %>
            <i class="fa-regular fa-square-caret-right"></i>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<h1><%= @challenge.name %></h1>
<%= link_to "← Back", challenge_path(@challenge) %>

<% @challenge.messages.each do |message| %>
  <p>
    <strong><%= message.role %></strong>
    <% if message.file.attached? %>
      <strong>File:</strong>
      <%= link_to message.file.filename, rails_blob_path(message.file, disposition: "attachment") %>
    <% end %>
    <%= raw(render_markdown(message.content)) %>
  </p>
<% end %>

app/views/messages/new.html.erb
<h1><%= @challenge.name %></h1>

<%= simple_form_for [@challenge, @message] do |f| %>
  <%= f.input :content, placeholder: "Ask a question", required: true, label: false %>
  <%= f.input :file, as: :file, label: "Upload a file (PDF, image, or audio)" %>
  <%= f.button :submit, 'Ask LLM', class: 'btn btn-primary' %>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidenav.html.erb
<ul class="position-sticky sticky-top nav flex-column">
  <li class="nav-item">
    <%= link_to "#",
                class: "nav-link text-dark",
                data: { action: 'click->toggle#call' } do %>
      <i class="fa-regular fa-square-caret-left"></i>
    <% end %>
  </li>
  <% challenges.each do |challenge| %>
    <li class="nav-item">
      <%= link_to challenge.name, challenge_path(challenge), class: "nav-link text-dark" %>
    </li>
  <% end %>
</ul>